### ISSUE TITLE
MrPeeps does not open

### ISSUE THREAD

**Issue by n0toose** [HaikuArchives/MrPeeps#2]
As of the R1/beta1 release (Revision hrev52295+132, x86_64), MrPeeps crashes at launch.

![image](https://user-images.githubusercontent.com/30193966/71812987-2c473500-3081-11ea-8674-8932b882f550.png)

**Comment by cafeina-software** [comment]
It still crashes in r1beta4 hrev56578+65 x86_64

**Comment by cafeina-software** [comment]
Crash report: [MrPeeps-1619-debug-15-01-2023-00-29-57.report](https://github.com/HaikuArchives/MrPeeps/files/10419167/MrPeeps-1619-debug-15-01-2023-00-29-57.report.txt)
